title:            "Richard Laugesen"
title_seperator:  "-"
description:      "Make robots that forecast water. Tinker with business."
url: 		  "http://richardlaugesen.com"
baseurl:
theme: 		  "sparrow-jekyll-theme"
favicon:	  "/assets/images/richard-square.jpg"
avatar:		  "/assets/images/richard-square.jpg"
og_image:	  "/assets/images/richard-square.jpg"
locale:		  "en"
encoding:	  "utf-8"

author:
  name:		  "Richard Laugesen"

comments:	  false
disqus:
  shortname:	  "richardlaugesen"

atom_feed:
  path:

twitter:
  username:	  "richardlaugesen"

linkedin:
  username:	  "richardlaugesen"

email:		  "hello@richardlaugesen.com"

analytics:
  google:
    tracking_id:  "UA-89112715-1"

timezone:    	  "Australia/Canberra"
permalink:   	  "/writing/:title/"

gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.jsx
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Front matter defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      comments: false
      share: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      share: false
